#!/usr/bin/env node
/**
 * install-task.mjs — register the watcher as a Windows Scheduled Task so it
 * survives reboots, logoffs and sleep (a plain background process does not).
 *
 * The task re-runs `watcher.mjs` every N minutes; the watcher's single-instance
 * lock makes repeated launches no-ops while one is alive. Combined with the
 * watcher's startup catch-up scan and persisted schedule state, this guarantees
 * a missed reset (PC asleep or rebooted at reset time) is recovered within one
 * task interval after the machine is back.
 *
 * Usage (Windows):
 *   node scripts/install-task.mjs --project-dir <~/.claude/projects/XXX> --cwd <projectCwd>
 *                                 [--name ClaudeAutoResume] [--every 5] [--extra "--delay-min 5"]
 *   node scripts/install-task.mjs --uninstall [--name ClaudeAutoResume]
 *
 * On macOS/Linux this prints an equivalent cron line instead.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const WATCHER = path.resolve(here, '..', 'watcher.mjs');

const argv = process.argv.slice(2);
function arg(name, def = null) {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : def;
}
const has = (name) => argv.includes(`--${name}`);

const NAME = arg('name', 'ClaudeAutoResume');
const EVERY = Number(arg('every', '5'));
const PROJECT_DIR = arg('project-dir');
const CWD = arg('cwd', process.cwd());
const EXTRA = arg('extra', '');

if (has('uninstall')) {
  if (process.platform !== 'win32') {
    console.log(`Remove the cron line for ${WATCHER} manually (crontab -e).`);
    process.exit(0);
  }
  const r = spawnSync('schtasks', ['/delete', '/tn', NAME, '/f'], { encoding: 'utf8' });
  console.log(r.stdout || r.stderr);
  process.exit(r.status || 0);
}

if (!PROJECT_DIR || !fs.existsSync(PROJECT_DIR)) {
  console.error('pass --project-dir <existing ~/.claude/projects/XXX directory>');
  process.exit(1);
}

const nodeBin = process.execPath;
const watcherArgs = `--project-dir "${PROJECT_DIR}" --cwd "${CWD}"${EXTRA ? ' ' + EXTRA : ''}`;

if (process.platform !== 'win32') {
  console.log('Non-Windows platform — add this cron line (crontab -e):');
  console.log(`*/${EVERY} * * * * "${nodeBin}" "${WATCHER}" ${watcherArgs} >/dev/null 2>&1`);
  process.exit(0);
}

// schtasks /tr is limited to 261 characters — use a generated .cmd wrapper so
// the task command stays short regardless of path lengths.
const wrapperDir = path.join(os.homedir(), '.claude', 'auto-resume');
fs.mkdirSync(wrapperDir, { recursive: true });
const wrapper = path.join(wrapperDir, `run-${NAME}.cmd`);
fs.writeFileSync(wrapper, [
  '@echo off',
  'rem Generated by claude-auto-resume install-task.mjs — safe to regenerate.',
  `"${nodeBin}" "${WATCHER}" ${watcherArgs}`,
  '',
].join('\r\n'));

const create = spawnSync('schtasks', [
  '/create', '/f',
  '/tn', NAME,
  '/sc', 'minute',
  '/mo', String(EVERY),
  '/tr', `"${wrapper}"`,
], { encoding: 'utf8' });
console.log((create.stdout || '') + (create.stderr || ''));
if (create.status !== 0) process.exit(create.status || 1);

// Harden the task settings: allow on battery, and run a missed start as soon as
// the machine is available again (post-sleep / post-boot catch-up).
const tune = spawnSync('powershell.exe', ['-NoProfile', '-Command',
  `Set-ScheduledTask -TaskName '${NAME}' -Settings (New-ScheduledTaskSettingsSet ` +
  `-AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable ` +
  `-MultipleInstances IgnoreNew) | Out-Null`], { encoding: 'utf8' });
if (tune.status !== 0) console.warn('warning: could not tune task power settings:', tune.stderr || tune.stdout);

console.log(`Task "${NAME}" created: runs every ${EVERY} min (watcher is single-instance).`);
console.log(`Wrapper: ${wrapper}`);
console.log('Verify with: schtasks /query /tn ' + NAME + ' /v /fo LIST');
